# Generated by Django 5.1 on 2024-09-02 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(max_length=255, verbose_name='Nombre del Programa')),
                ('codigo_programa', models.CharField(max_length=50, unique=True, verbose_name='Código del Programa')),
            ],
            options={
                'verbose_name': 'Programa Académico',
                'verbose_name_plural': 'Programas Académicos',
            },
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario_Bienestar', 'Usuario Bienestar'), ('Estudiante', 'Estudiante')], default=2024, max_length=20, verbose_name='Rol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario_Bienestar', 'Usuario Bienestar'), ('Estudiante', 'Estudiante')], default=2024, max_length=20, verbose_name='Rol'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField(verbose_name='Semestre')),
                ('horas_acumuladas', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Horas Acumuladas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL)),
                ('programa_academico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.programaacademico')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='UsuarioBienestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_academica', models.CharField(choices=[('Dimensión 1', 'Dimensión 1'), ('Dimensión 2', 'Dimensión 2'), ('Dimensión 3', 'Dimensión 3'), ('Dimensión 4', 'Dimensión 4')], max_length=50, verbose_name='Dimensión Académica')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_bienestar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Bienestar',
                'verbose_name_plural': 'Usuarios de Bienestar',
            },
        ),
    ]
