# Generated by Django 5.1 on 2024-09-03 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_estudiante_programa_academico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioBienestar',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dimension_academica', models.CharField(max_length=255, verbose_name='Dimensión Académica')),
            ],
            options={
                'verbose_name': 'Usuario Bienestar',
                'verbose_name_plural': 'Usuarios Bienestar',
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='user',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario_Bienestar', 'Usuario Bienestar'), ('Estudiante', 'Estudiante')], default='Estudiante', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario_Bienestar', 'Usuario Bienestar'), ('Estudiante', 'Estudiante')], default='Estudiante', max_length=20, verbose_name='Rol'),
        ),
    ]
