# Generated by Django 5.1 on 2024-10-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usuariobienestar_historicaluser_celular_user_celular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='horas_acumuladas',
            new_name='accumulated_hours',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='semestre',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='historicaluser',
            old_name='celular',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='celular',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='usuariobienestar',
            old_name='dimension_academica',
            new_name='dimension',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default=1, max_length=1, verbose_name='Género'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='identification',
            field=models.CharField(db_index=True, default=1, max_length=20, verbose_name='Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='type_document',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=2, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default=1, max_length=1, verbose_name='Género'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='type_document',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=2, verbose_name='Tipo de documento'),
        ),
    ]
