# Generated by Django 5.1 on 2024-10-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_horas_acumuladas_estudiante_accumulated_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='identification',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Documento'),
        ),
    ]
