# Generated by Django 5.1 on 2024-11-10 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_historicaluser_identification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Programa Académico',
                'verbose_name_plural': 'Programas Académicos',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='academic_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.academicprogram'),
            preserve_default=False,
        ),
    ]
