# Generated by Django 5.1 on 2024-11-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_academicprogram_estudiante_academic_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprogram',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
    ]
