# Generated by Django 5.1 on 2024-09-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='programdimension',
            new_name='program_dimension',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='subprogramdimension',
            new_name='subprogram_dimension',
        ),
        migrations.RenameField(
            model_name='historicalactivity',
            old_name='programdimension',
            new_name='program_dimension',
        ),
        migrations.RenameField(
            model_name='historicalactivity',
            old_name='subprogramdimension',
            new_name='subprogram_dimension',
        ),
        migrations.RenameField(
            model_name='historicalsubprogramdimension',
            old_name='programdimension',
            new_name='program_dimension',
        ),
        migrations.RenameField(
            model_name='subprogramdimension',
            old_name='programdimension',
            new_name='program_dimension',
        ),
        migrations.AddField(
            model_name='activity',
            name='count_hours',
            field=models.IntegerField(default=2, verbose_name='Cantidad de horas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='count_hours',
            field=models.IntegerField(default=4, verbose_name='Cantidad de horas'),
            preserve_default=False,
        ),
    ]
