# Generated by Django 5.1 on 2024-11-23 22:07

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_programdimension_activity_program_dimension_and_more'),
        ('users', '0009_documenttype_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='qr_code_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador QR'),
        ),
        migrations.AddField(
            model_name='historicalactivity',
            name='qr_code_identifier',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Identificador QR'),
        ),
        migrations.CreateModel(
            name='HistoricalAttandenceActivity',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creaqcion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de eliminacion')),
                ('attendance_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asistencia')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activity', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='activities.activity')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.estudiante')),
            ],
            options={
                'verbose_name': 'historical Registro de Actividad',
                'verbose_name_plural': 'historical Registros de Actividades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AttandenceActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creaqcion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminacion')),
                ('attendance_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asistencia')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.estudiante')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividades',
                'unique_together': {('activity', 'student')},
            },
        ),
    ]
